Portfolio.UI/Areas/Dashboard/Controllers/DegreeController.cs
using FluentValidation.Results;
using Portfolio.BLL.Concrete;
using Portfolio.BLL.ValidationRules;
using Portfolio.DAL.EntityFramework;
using Portfolio.ENTITY.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolio.UI.Areas.Dashboard.Controllers
{
    public class DegreeController : Controller
    {
        DegreeManager degreeManager = new DegreeManager(new EfDegreeRepository());
        DegreeValidator degreeValidator = new DegreeValidator();
        // GET: Dashboard/Degree
        public ActionResult Index()
        {
            return View(degreeManager.List());
        }

        [HttpGet]
        public PartialViewResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(Degree p)
        {
            ValidationResult validationResult = degreeValidator.Validate(p);
            if (validationResult.IsValid)
            {
                p.IsActive = true;
                p.CreateDate = DateTime.Now;
                degreeManager.Add(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View(p);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(degreeManager.Get(id));
        }

        [HttpPost]
        public ActionResult Edit(Degree p)
        {
            ValidationResult validationResult = degreeValidator.Validate(p);
            if (validationResult.IsValid)
            {
                var key = degreeManager.Get(p.Id);
                p.IsActive = key.IsActive;
                p.CreateDate = key.CreateDate;
                degreeManager.Update(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View(p);
            }
        }

        public ActionResult Delete(int id)
        {
            degreeManager.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Portfolio.UI/Areas/Dashboard/Views/Degree/Create.cshtml
@model Portfolio.ENTITY.Concrete.Degree

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Dashboard/Views/Shared/DashboardLayout.cshtml";
}

@using (Html.BeginForm("Create", "Degree", FormMethod.Post))
{
    <div class="form-group">
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder = "Ünvan" })
        @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-outline-danger">Create Degree</button>
    </div>
}

Portfolio.UI/Areas/Dashboard/Views/Degree/Edit.cshtml
@model Portfolio.ENTITY.Concrete.Degree

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Dashboard/Views/Shared/DashboardLayout.cshtml";
}

@using (Html.BeginForm("Edit", "Degree", FormMethod.Post))
{
    <div class="form-group">
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder = "Ünvan" })
        @Html.ValidationMessageFor(x => x.Name,"", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-outline-danger">Edit Degree</button>
    </div>
}

Portfolio.UI/Areas/Dashboard/Views/Degree/Index.cshtml
@model List<Portfolio.ENTITY.Concrete.Degree>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Dashboard/Views/Shared/DashboardLayout.cshtml";

    int i = 0;
}


@if (Model.Count() == 0)
{
    @Html.Partial("Alert")
}

<div class="section-wrapper mb-4">
    <div class="table-responsive">
        <table class="table mg-b-0">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    i++;
                    <tr>
                        <td>@i</td>
                        <td>@item.Name</td>
                        <td>@item.CreateDate.ToString("dd MM yyyy HH:mm")</td>
                        <td>@Html.Raw(item.IsActive == true ? "<i class='fa fa-check'></i>" : "<i class='fa fa-close'></i>")</td>
                        <td>
                            <a href="@Url.Action("Edit", new { id = item.Id })"><i class="fa fa-pencil mr-3"></i></a>
                            <a href="@Url.Action("Delete", new { id = item.Id })"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<a href="@Url.Action("Create")" class="btn btn-outline-danger btn-block mg-b-10"><i class="fa fa-paper-plane mg-r-5"></i>Create</a>