Portfolio.UI/Areas/Dashboard/Controllers/ContactController.cs
using Portfolio.BLL.Concrete;
using Portfolio.DAL.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolio.UI.Areas.Dashboard.Controllers
{
    public class ContactController : Controller
    {
        ContactManager contactManager = new ContactManager(
            new EfContactRepository(),
            new EfInformationRepository());
        // GET: Dashboard/Contact
        public ActionResult Index()
        {
            return View(contactManager.List());
        }
    }
}

Portfolio.UI/Controllers/ContactController.cs
using Portfolio.BLL.Concrete;
using Portfolio.DAL.EntityFramework;
using Portfolio.ENTITY.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolio.UI.Controllers
{
    public class ContactController : Controller
    {
        ContactManager contactManager = new ContactManager(new EfContactRepository(),
                                                           new EfInformationRepository());
        // GET: Contact
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Contact p)
        {
            p.IsActive = true;
            p.CreateDate = DateTime.Now;
            contactManager.Add(p);
            return RedirectToAction("Index");
        }

        public PartialViewResult Address()
        {
            return PartialView(contactManager.GetAddress());
        }
    }
}

Portfolio.UI/Views/Contact/Index.cshtml
@model Portfolio.ENTITY.Concrete.Contact

@{
    ViewBag.Title = "Contact me";
    Layout = "~/Views/Shared/HomeLayout.cshtml";
}

<div class="section-container">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="section-container-spacer text-center">
                    <h1 class="h2">03 : @ViewBag.Title</h1>
                </div>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">

                        <div class="row">
                            @using (Html.BeginForm("Index", "Contact", FormMethod.Post, new { @class = "reveal-content" }))
                            {
                            <div class="col-md-7">
                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.FullName, new { @class = "form-control", placeholder = "FullName" })
                                </div>

                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder = "Email" })
                                </div>

                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control", placeholder = "Subject" })
                                </div>

                                <div class="form-group">
                                    @Html.TextAreaFor(x => x.Message, 5, 0, new { @class = "form-control", placeholder = "Enter your message" })
                                </div>

                                <button type="submit" class="btn btn-default btn-lg">Send</button>
                            </div>
                            }
                            @Html.Action("Address")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>