Portfolio.UI/Areas/Dashboard/Controllers/AboutController.cs
using FluentValidation.Results;
using Portfolio.BLL.Concrete;
using Portfolio.BLL.ValidationRules;
using Portfolio.DAL.EntityFramework;
using Portfolio.ENTITY.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolio.UI.Areas.Dashboard.Controllers
{
    public class AboutController : Controller
    {
        AboutManager aboutManager = new AboutManager(new EfAboutRepository());
        AboutValidator aboutValidator = new AboutValidator();
        // GET: Dashboard/About
        public ActionResult Index()
        {
            return View(aboutManager.List());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(About p)
        {
            ValidationResult validationResult = aboutValidator.Validate(p);
            if (validationResult.IsValid)
            {
                p.IsActive = true;
                p.CreateDate = DateTime.Now;
                aboutManager.Add(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View(p);
            }
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return View(aboutManager.Get());
        }

        [HttpPost]
        public ActionResult Edit(About p)
        {
            ValidationResult validationResult = aboutValidator.Validate(p);
            if (validationResult.IsValid)
            {
                var key = aboutManager.Get();
                p.IsActive = key.IsActive;
                p.CreateDate = key.CreateDate;
                aboutManager.Update(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View(p);
            }
        }
    }
}

Portfolio.UI/Controllers/AboutController.cs
using Portfolio.BLL.Concrete;
using Portfolio.DAL.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolio.UI.Controllers
{
    public class AboutController : Controller
    {
        AboutManager aboutManager = new AboutManager(new EfAboutRepository());
        // GET: About
        public ActionResult Index()
        {
            return View(aboutManager.Get());
        }
    }
}

Portfolio.UI/Areas/Dashboard/Views/About/Create.cshtml
@model Portfolio.ENTITY.Concrete.About

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Dashboard/Views/Shared/DashboardLayout.cshtml";
}

@using (Html.BeginForm("Create", "About", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.TextBoxFor(x => x.Title, new { @class = "form-control", placeholder = "Başlık" })
        @Html.ValidationMessageFor(x => x.Title, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.TextAreaFor(x => x.Description, 10, 0, new { @class = "form-control", placeholder = "Açıklama" })
        @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.TextBoxFor(x => x.Image, new { @class = "form-control", type = "file" })
        @Html.ValidationMessageFor(x => x.Image, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-outline-danger">Create About</button>
    </div>
}

Portfolio.UI/Areas/Dashboard/Views/About/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Dashboard/Views/Shared/DashboardLayout.cshtml";
}

<h2>Edit</h2>

Portfolio.UI/Areas/Dashboard/Views/About/Index.cshtml
@model List<Portfolio.ENTITY.Concrete.About>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Dashboard/Views/Shared/DashboardLayout.cshtml";
}

@foreach (var item in Model)
{
    <div class="media media-demo mb-4">
        <div class="media-body mg-r-50">
            <h1 class="tx-info mg-b-20">@item.Title</h1>
            @Html.Raw(item.Description)
        </div>
        <img src="@item.Image" class="d-flex wd-300" alt="Image">
    </div>
}

<a href="@Url.Action("Edit")" class="btn btn-outline-danger btn-block mg-b-10"><i class="fa fa-book mg-r-5"></i>Edit</a>


@if (Model.Count() != 1)
{
    <a href="@Url.Action("Create")" class="btn btn-outline-danger btn-block mg-b-10"><i class="fa fa-paper-plane mg-r-5"></i>Create</a>
}